idf_component_register(
    SRCS
        "main.c"
        "neopixel.c"
        "endstop.c"
        "config_loader.c"
        "gatt_server.c"
        "ota_handler.c"
    INCLUDE_DIRS
        "."
        "../../shared/protocol"
    REQUIRES
        led_strip
        bt
        nvs_flash
        spiffs
        app_update
        json
        esp_driver_gpio
)
